apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      name: todoapp 
      labels:
        app: todoapp
    spec:
      containers:
      - name: main
        image: todoapp
        imagePullPolicy: Never
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "3000"