apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      name: todoapi 
      labels:
        app: todoapi
    spec:
      containers:
      - name: main
        image: todo-api
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: todoapicm
        ports:
          - containerPort: 3000
