apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-demo
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp 
      labels:
        app: myapp
    spec:
      containers:
      - name: main
        image: todo-front
        imagePullPolicy: Never
        ports:
          - containerPort: 80