pipeline {
    agent {
        docker { image 'gradle:6.6.1-jre14-openj9' }
    }

    stages {
        stage ('Compile') {
            steps {
              sh label: 'Compilar codigo', script: 'cd calculator && gradle compileJava -g gradle-user-home'
            }        
        }

        stage ('Unit Tests') {
            steps {
              sh label: 'Ejecutar test unitarios', script: 'cd calculator && gradle test -g gradle-user-home'
            }
        }
    }
      post {
        cleanup {
            //Clean Workspace
            cleanWs()
        }
    }
}

