apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    app: postgres
    type: local
spec:
  storageClassName: "postgres"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"