apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      name: todoapp 
      labels:
        app: todoapp
    spec:
      containers:
      - name: main
        image: todoapp
        imagePullPolicy: Never
        env:
          - name: NODE_ENV
            value: "develop"
          - name: PORT 
            value: "3000"
          - name: DB_HOST
            value: "10.100.235.72"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "todos_db"
          - name: DB_VERSION
            value: "10.4"


